defmodule ExAccounting.Repo.Migrations.CreateAccountingDocumentItems do
  use Ecto.Migration

  def change do
    create table(:accounting_document_items) do
      add :fiscal_year, :integer
      add :accounting_area, :string
      add :accounting_document_number, :integer
      add :accounting_unit, :string
      add :accounting_document_item_number, :integer
      add :debit_credit, :string
      add :document_type, :string
      add :posting_date, :date
      add :accounting_period, :integer
      add :document_date, :date
      add :entry_date, :date
      add :entered_at, :time
      add :entered_by, :string
      add :posted_by, :string
      add :reverse_document_indicator, :string
      add :reverse_document_accounting_unit, :string
      add :reverse_document_fiscal_year, :integer
      add :reverse_document_accounting_document, :integer
      add :reverse_document_accounting_document_item, :integer
      add :reverse_document_accounting_period, :integer
      add :clearing_document_indicator, :string
      add :clearing_document_accounting_unit, :string
      add :clearing_document_fiscal_year, :integer
      add :clearing_document_accounting_document, :integer
      add :clearing_document_accounting_document_item, :integer
      add :cleairng_document_accounting_period, :integer
      add :reference_area, :string
      add :reference_key, :string
      add :general_ledger_account_transaction_type, :string
      add :general_ledger_account, :string
      add :vendor_transaction_type, :string
      add :vendor, :string
      add :customer_transaction_type, :string
      add :customer, :string
      add :fixed_asset_transaction_type, :string
      add :fixed_asset, :string
      add :payment_service_trainsaction_type, :string
      add :payment_service, :string
      add :profit_center_transaction_type, :string
      add :profit_center, :string
      add :functional_area_transaction_type, :string
      add :functional_area, :string
      add :cost_center_transaction_type, :string
      add :cost_center, :string
      add :order_transaction_type, :string
      add :order, :string
      add :wbs_element_transaction_type, :string
      add :wbs_element, :string
      add :sales_order_transaction_type, :string
      add :sales_order, :string
      add :sales_order_item_transaction_type, :string
      add :sales_order_item, :string
      add :partner_accounting_unit, :string
      add :partner_profit_center, :string
      add :partner_cost_center, :string
      add :partner_functional_area, :string
      add :accounting_unit_currency, :string
      add :amount_in_accounting_unit_currency, :decimal
      add :exchange_rate_type_to_accounting_unit_currency, :string
      add :exchange_rate_to_accounting_unit_currency, :decimal
      add :date_of_exchange_rate_to_accounting_unit_currency, :date
      add :transaction_currency, :string
      add :amount_in_transaction_currency, :decimal
      add :accounting_area_currency, :string
      add :amount_in_accounting_area_currency, :decimal
      add :exchange_rate_type_to_accounting_area_currency, :string
      add :exchange_rate_to_accounting_area_currency, :decimal
      add :date_of_exchagne_rate_to_accounting_area_currency, :date
      add :offsetting_general_ledger_account, :string
      add :offsetting_vendor, :string
      add :offsetting_customer, :string
      add :offsetting_fixed_asset, :string
      add :offsetting_material, :string
      add :offsetting_bank, :string
      add :offsetting_payment_service, :string
      add :offsetting_cost_center, :string
      add :offsetting_functional_area, :string
      add :offsetting_wbs_element, :string
      add :vat_code, :string
      add :vat_amount_of_accounting_unit_currency, :decimal
      add :vat_amount_of_transaction_currency, :decimal
      add :vat_amount_of_accounting_area_currency, :decimal
      add :vat_base_amount_of_accounting_unit_currency, :decimal
      add :vat_base_amount_of_transaction_currency, :decimal
      add :vat_base_amount_of_accounting_area_currency, :decimal
    end
  end
end
